application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: mainpage.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest